return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "1.0.3",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 15,
  height = 6,
  tilewidth = 32,
  tileheight = 32,
  nextobjectid = 65,
  properties = {},
  tilesets = {
    {
      name = "Terrain",
      firstgid = 1,
      filename = "../assets/tilesets/terrain.tsx",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      image = "../assets/tilesets/terrain.png",
      imagewidth = 608,
      imageheight = 416,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 247,
      tiles = {}
    },
    {
      name = "Decorations",
      firstgid = 248,
      filename = "../assets/tilesets/decorations.tsx",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      image = "../assets/tilesets/decorations.png",
      imagewidth = 224,
      imageheight = 256,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 56,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      name = "Terrain",
      x = 0,
      y = 0,
      width = 15,
      height = 6,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "lua",
      data = {
        41, 41, 27, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 28,
        27, 60, 61, 135, 136, 136, 136, 136, 136, 136, 136, 136, 136, 137, 40,
        42, 135, 136, 161, 155, 155, 155, 155, 141, 174, 142, 155, 155, 156, 40,
        42, 173, 174, 142, 155, 155, 155, 155, 156, 25, 173, 174, 174, 175, 40,
        46, 22, 23, 173, 174, 174, 174, 174, 175, 106, 22, 22, 22, 22, 47,
        41, 41, 46, 22, 22, 22, 22, 22, 22, 47, 41, 41, 41, 41, 41
      }
    },
    {
      type = "tilelayer",
      name = "Decorations",
      x = 0,
      y = 0,
      width = 15,
      height = 6,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 271, 272, 0, 0, 0, 0, 0, 0, 0, 0, 256, 0,
        0, 284, 285, 278, 279, 0, 0, 0, 0, 0, 0, 284, 285, 270, 0,
        0, 291, 292, 0, 0, 264, 266, 0, 257, 0, 0, 291, 292, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 257, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      name = "Objects",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 22,
          name = "Entry",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 72,
          width = 46,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "Exit",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 72,
          width = 46,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "Pig",
          type = "insideCrate",
          shape = "rectangle",
          x = 272,
          y = 144,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "Pig",
          type = "normal",
          shape = "rectangle",
          x = 296,
          y = 80,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "Bomb",
          type = "",
          shape = "rectangle",
          x = 168,
          y = 80,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "Pig",
          type = "normal",
          shape = "rectangle",
          x = 200,
          y = 80,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "Crate",
          type = "2",
          shape = "rectangle",
          x = 32,
          y = 112,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "Crate",
          type = "1",
          shape = "rectangle",
          x = 320,
          y = 112,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "Crate",
          type = "2",
          shape = "rectangle",
          x = 320,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "Crate",
          type = "1",
          shape = "rectangle",
          x = 432,
          y = 112,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "Collisions",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 64,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 128,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 160,
          width = 192,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 96,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 128,
          width = 128,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 32,
          width = 32,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 32,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 0,
          width = 352,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 96,
          width = 64,
          height = 12,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "Sensors",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 62,
          name = "",
          type = "2",
          shape = "rectangle",
          x = 256,
          y = 128,
          width = 32,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "2",
          shape = "rectangle",
          x = 256,
          y = 96,
          width = 32,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
